version: '2'
services:
  php-install:
      image: ucreateit/php7.2:v0.1
      links:
          - pgsql
  pgsql:
      image: postgres:10.3-alpine
      environment:
        DB_CONNECTION: pgsql
        DB_HOST: pgsql
        DB_PORT: 5434
        DB_DATABASE: test
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
      ports:
        - "5434:5432"

  pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: admin@pgadmin.com
      ports:
        - "5000:80"
      volumes:
        - ./pgadmin:/var/lib/pgadmin